### ISSUE TITLE
Mock Globus client should not inherit from real globus client

### ISSUE THREAD

**Issue by dylanmcreynolds** [als-computing/splash_flows_globus#27]
https://github.com/als-computing/splash_flows_globus/blob/a2b20e1375ae11e58fbc3552a8745d85482bbc7c/orchestration/_tests/test_globus_flow.py#L104

**Comment by dylanmcreynolds** [comment]
@davramov  can you address this?

**Comment by davramov** [comment]
I have addressed in my PR: https://github.com/als-computing/splash_flows_globus/pull/29
