### ISSUE TITLE
Dispatcher enhancements

### ISSUE THREAD

**Issue by dylanmcreynolds** [als-computing/splash_flows_globus#42]
A few ideas from testing at the beamline:

- [ ] Shouldn't have to pass file name, since the file name is already in the path
- [ ] Should remove `send_to_nersc` and `send_to_alcf`. `is_export_control` should the only one, and it should decide whether to transfer anywhere

**Comment by davramov** [comment]
Addressing this in the following PR: https://github.com/als-computing/splash_flows_globus/pull/43

**Comment by davramov** [comment]
Closing this because the changes have been addressed in the most recent release: https://github.com/als-computing/splash_flows_globus/releases/tag/v0.3.7
